version: "3"

services:
  app:
    build: .
    command: /app/up.sh
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: api.settings
