# Generated by Django 5.2.5 on 2025-08-14 08:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2025)])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.album')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='players',
            field=models.ManyToManyField(related_name='albums', through='api.AlbumPlayers', to='api.player'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_song')],
            },
        ),
        migrations.CreateModel(
            name='AlbumSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_album_order', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asongs', to='api.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salbums', to='api.song')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='albums', through='api.AlbumSongs', to='api.song'),
        ),
        migrations.AddConstraint(
            model_name='albumplayers',
            constraint=models.UniqueConstraint(fields=('album', 'player'), name='unique_album_player'),
        ),
        migrations.AddConstraint(
            model_name='albumsongs',
            constraint=models.UniqueConstraint(fields=('album', 'song'), name='unique_album_song'),
        ),
        migrations.AddConstraint(
            model_name='albumsongs',
            constraint=models.UniqueConstraint(fields=('album', 'in_album_order'), name='unique_album_order'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('name', 'year'), name='unique_album'),
        ),
    ]
